---
- hosts: all
  roles:
    - role: bloodymage.autonomy.config_environment
      tags:
        - always


- hosts: all
  roles:
    - role: bloodymage.maintenance.service_restart
      tags:
        - never
        - restart-services

- hosts: all
  serial: 1
  roles:
    - role: bloodymage.maintenance.reboot
      tags:
        - never
        - reboot
